version: '3.3'
services:
  frontend:
    image: pyflaskserver:latest
    restart: always
    networks:
     - web
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=web"
      - "traefik.backend=root"
      - "traefik.first.frontend.rule=Host:klodsen.simon.stiil.dk"
  backend:
    image: pyflaskserver:latest
    restart: always
    networks:
      - web
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=web"
      - "traefik.backend=root"
      - "traefik.first.frontend.rule=Host:klodsen.simon.stiil.dk"
  api:
    image: pyflaskserver:latest
    restart: always
    networks:
     - web
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=web"
      - "traefik.backend=root"
      - "traefik.first.frontend.rule=Host:klodsen.simon.stiil.dk"

      - "traefik.first.frontend.rule1=Host:www.test.mydomain.com;PathPrefixStrp:/_"